stages:
  - test

variables:
  GITLAB_MAKE: "make -f .gitlab.mk"

# Jobs templates

.deploy_template: &deploy_definition
  stage: test
  tags:
    - deploy
  script:
    - ${GITLAB_MAKE} deploy

.deploy_test_template: &deploy_test_definition
  stage: test
  tags:
    - deploy_test
  script:
    - ${GITLAB_MAKE} deploy

centos_7_deploy:
  <<: *deploy_test_definition
  variables:
    OS: 'el'
    DIST: '7'

fedora_30_deploy:
  <<: *deploy_test_definition
  variables:
    OS: 'fedora'
    DIST: '30'

ubuntu_18_04_deploy:
  <<: *deploy_definition
  variables:
    OS: 'ubuntu'
    DIST: 'bionic'

debian_9_deploy:
  <<: *deploy_definition
  variables:
    OS: 'debian'
    DIST: 'stretch'
